/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportGroupsRouteImport } from './routes/support-groups'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourceLibraryRouteImport } from './routes/resource-library'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyAffirmationRouteImport } from './routes/daily-affirmation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtAGlanceRouteImport } from './routes/at-a-glance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutBackupRouteImport } from './routes/about-backup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeBaseIndexRouteImport } from './routes/knowledge-base.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as KnowledgeBaseIdRouteImport } from './routes/knowledge-base.$id'
import { Route as ArticlesHelpingChildrenDealWithGriefRouteImport } from './routes/articles.helping-children-deal-with-grief'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUrlMonitorRouteImport } from './routes/admin.url-monitor'
import { Route as AdminMemoryRouteImport } from './routes/admin.memory'
import { Route as AdminMcpServersRouteImport } from './routes/admin.mcp-servers'
import { Route as AdminKnowledgeSourcesRouteImport } from './routes/admin.knowledge-sources'
import { Route as AdminKnowledgeBaseRouteImport } from './routes/admin.knowledge-base'
import { Route as AdminJournalPromptsRouteImport } from './routes/admin.journal-prompts'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminEmailCapturesRouteImport } from './routes/admin.email-captures'
import { Route as AdminAiUsageRouteImport } from './routes/admin.ai-usage'
import { Route as AdminAiModelsRouteImport } from './routes/admin.ai-models'
import { Route as AdminInsightsIndexRouteImport } from './routes/admin.insights.index'
import { Route as AdminConversationsIndexRouteImport } from './routes/admin.conversations.index'
import { Route as AdminAgentsIndexRouteImport } from './routes/admin.agents.index'
import { Route as AdminSafetyPoliciesRouteImport } from './routes/admin.safety.policies'
import { Route as AdminSafetyGuardrailsRouteImport } from './routes/admin.safety.guardrails'
import { Route as AdminSafetyEscalationsRouteImport } from './routes/admin.safety.escalations'
import { Route as AdminSafetyAuditLogRouteImport } from './routes/admin.safety.audit-log'
import { Route as AdminOpsTeamRouteImport } from './routes/admin.ops.team'
import { Route as AdminOpsRolesRouteImport } from './routes/admin.ops.roles'
import { Route as AdminOpsNotificationsRouteImport } from './routes/admin.ops.notifications'
import { Route as AdminOpsChangelogRouteImport } from './routes/admin.ops.changelog'
import { Route as AdminOpsBillingRouteImport } from './routes/admin.ops.billing'
import { Route as AdminOpsApiKeysRouteImport } from './routes/admin.ops.api-keys'
import { Route as AdminInsightsThemesRouteImport } from './routes/admin.insights.themes'
import { Route as AdminInsightsSentimentRouteImport } from './routes/admin.insights.sentiment'
import { Route as AdminInsightsFunnelRouteImport } from './routes/admin.insights.funnel'
import { Route as AdminInsightsCohortsRouteImport } from './routes/admin.insights.cohorts'
import { Route as AdminConversationsFlaggedRouteImport } from './routes/admin.conversations.flagged'
import { Route as AdminConversationsIdRouteImport } from './routes/admin.conversations.$id'
import { Route as AdminContentEmailTemplatesRouteImport } from './routes/admin.content.email-templates'
import { Route as AdminContentCalendarRouteImport } from './routes/admin.content.calendar'
import { Route as AdminAgentsAgentIdRouteImport } from './routes/admin.agents.$agentId'
import { Route as AdminContentArticlesIndexRouteImport } from './routes/admin.content.articles.index'
import { Route as AdminContentArticlesIdRouteImport } from './routes/admin.content.articles.$id'

const SupportGroupsRoute = SupportGroupsRouteImport.update({
  id: '/support-groups',
  path: '/support-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceLibraryRoute = ResourceLibraryRouteImport.update({
  id: '/resource-library',
  path: '/resource-library',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyAffirmationRoute = DailyAffirmationRouteImport.update({
  id: '/daily-affirmation',
  path: '/daily-affirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtAGlanceRoute = AtAGlanceRouteImport.update({
  id: '/at-a-glance',
  path: '/at-a-glance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBackupRoute = AboutBackupRouteImport.update({
  id: '/about-backup',
  path: '/about-backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseIndexRoute = KnowledgeBaseIndexRouteImport.update({
  id: '/knowledge-base/',
  path: '/knowledge-base/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const KnowledgeBaseIdRoute = KnowledgeBaseIdRouteImport.update({
  id: '/knowledge-base/$id',
  path: '/knowledge-base/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesHelpingChildrenDealWithGriefRoute =
  ArticlesHelpingChildrenDealWithGriefRouteImport.update({
    id: '/articles/helping-children-deal-with-grief',
    path: '/articles/helping-children-deal-with-grief',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUrlMonitorRoute = AdminUrlMonitorRouteImport.update({
  id: '/url-monitor',
  path: '/url-monitor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemoryRoute = AdminMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMcpServersRoute = AdminMcpServersRouteImport.update({
  id: '/mcp-servers',
  path: '/mcp-servers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeSourcesRoute = AdminKnowledgeSourcesRouteImport.update({
  id: '/knowledge-sources',
  path: '/knowledge-sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeBaseRoute = AdminKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJournalPromptsRoute = AdminJournalPromptsRouteImport.update({
  id: '/journal-prompts',
  path: '/journal-prompts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailCapturesRoute = AdminEmailCapturesRouteImport.update({
  id: '/email-captures',
  path: '/email-captures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiUsageRoute = AdminAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiModelsRoute = AdminAiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsIndexRoute = AdminInsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsIndexRoute = AdminConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsIndexRoute = AdminAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyPoliciesRoute = AdminSafetyPoliciesRouteImport.update({
  id: '/safety/policies',
  path: '/safety/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyGuardrailsRoute = AdminSafetyGuardrailsRouteImport.update({
  id: '/safety/guardrails',
  path: '/safety/guardrails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyEscalationsRoute = AdminSafetyEscalationsRouteImport.update({
  id: '/safety/escalations',
  path: '/safety/escalations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyAuditLogRoute = AdminSafetyAuditLogRouteImport.update({
  id: '/safety/audit-log',
  path: '/safety/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsTeamRoute = AdminOpsTeamRouteImport.update({
  id: '/ops/team',
  path: '/ops/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsRolesRoute = AdminOpsRolesRouteImport.update({
  id: '/ops/roles',
  path: '/ops/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsNotificationsRoute = AdminOpsNotificationsRouteImport.update({
  id: '/ops/notifications',
  path: '/ops/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsChangelogRoute = AdminOpsChangelogRouteImport.update({
  id: '/ops/changelog',
  path: '/ops/changelog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsBillingRoute = AdminOpsBillingRouteImport.update({
  id: '/ops/billing',
  path: '/ops/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpsApiKeysRoute = AdminOpsApiKeysRouteImport.update({
  id: '/ops/api-keys',
  path: '/ops/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsThemesRoute = AdminInsightsThemesRouteImport.update({
  id: '/insights/themes',
  path: '/insights/themes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsSentimentRoute = AdminInsightsSentimentRouteImport.update({
  id: '/insights/sentiment',
  path: '/insights/sentiment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsFunnelRoute = AdminInsightsFunnelRouteImport.update({
  id: '/insights/funnel',
  path: '/insights/funnel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsCohortsRoute = AdminInsightsCohortsRouteImport.update({
  id: '/insights/cohorts',
  path: '/insights/cohorts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsFlaggedRoute =
  AdminConversationsFlaggedRouteImport.update({
    id: '/conversations/flagged',
    path: '/conversations/flagged',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConversationsIdRoute = AdminConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentEmailTemplatesRoute =
  AdminContentEmailTemplatesRouteImport.update({
    id: '/content/email-templates',
    path: '/content/email-templates',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentCalendarRoute = AdminContentCalendarRouteImport.update({
  id: '/content/calendar',
  path: '/content/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsAgentIdRoute = AdminAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentArticlesIndexRoute =
  AdminContentArticlesIndexRouteImport.update({
    id: '/content/articles/',
    path: '/content/articles/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentArticlesIdRoute = AdminContentArticlesIdRouteImport.update({
  id: '/content/articles/$id',
  path: '/content/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-backup': typeof AboutBackupRoute
  '/admin': typeof AdminRouteWithChildren
  '/at-a-glance': typeof AtAGlanceRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/daily-affirmation': typeof DailyAffirmationRoute
  '/dashboard': typeof DashboardRoute
  '/faqs': typeof FaqsRoute
  '/journal': typeof JournalRoute
  '/navigator': typeof NavigatorRoute
  '/onboarding': typeof OnboardingRoute
  '/resource-library': typeof ResourceLibraryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support-groups': typeof SupportGroupsRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/email-captures': typeof AdminEmailCapturesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/journal-prompts': typeof AdminJournalPromptsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/knowledge-sources': typeof AdminKnowledgeSourcesRoute
  '/admin/mcp-servers': typeof AdminMcpServersRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/url-monitor': typeof AdminUrlMonitorRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/helping-children-deal-with-grief': typeof ArticlesHelpingChildrenDealWithGriefRoute
  '/knowledge-base/$id': typeof KnowledgeBaseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/content/calendar': typeof AdminContentCalendarRoute
  '/admin/content/email-templates': typeof AdminContentEmailTemplatesRoute
  '/admin/conversations/$id': typeof AdminConversationsIdRoute
  '/admin/conversations/flagged': typeof AdminConversationsFlaggedRoute
  '/admin/insights/cohorts': typeof AdminInsightsCohortsRoute
  '/admin/insights/funnel': typeof AdminInsightsFunnelRoute
  '/admin/insights/sentiment': typeof AdminInsightsSentimentRoute
  '/admin/insights/themes': typeof AdminInsightsThemesRoute
  '/admin/ops/api-keys': typeof AdminOpsApiKeysRoute
  '/admin/ops/billing': typeof AdminOpsBillingRoute
  '/admin/ops/changelog': typeof AdminOpsChangelogRoute
  '/admin/ops/notifications': typeof AdminOpsNotificationsRoute
  '/admin/ops/roles': typeof AdminOpsRolesRoute
  '/admin/ops/team': typeof AdminOpsTeamRoute
  '/admin/safety/audit-log': typeof AdminSafetyAuditLogRoute
  '/admin/safety/escalations': typeof AdminSafetyEscalationsRoute
  '/admin/safety/guardrails': typeof AdminSafetyGuardrailsRoute
  '/admin/safety/policies': typeof AdminSafetyPoliciesRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/conversations/': typeof AdminConversationsIndexRoute
  '/admin/insights/': typeof AdminInsightsIndexRoute
  '/admin/content/articles/$id': typeof AdminContentArticlesIdRoute
  '/admin/content/articles/': typeof AdminContentArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-backup': typeof AboutBackupRoute
  '/at-a-glance': typeof AtAGlanceRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/daily-affirmation': typeof DailyAffirmationRoute
  '/dashboard': typeof DashboardRoute
  '/faqs': typeof FaqsRoute
  '/journal': typeof JournalRoute
  '/navigator': typeof NavigatorRoute
  '/onboarding': typeof OnboardingRoute
  '/resource-library': typeof ResourceLibraryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support-groups': typeof SupportGroupsRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/email-captures': typeof AdminEmailCapturesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/journal-prompts': typeof AdminJournalPromptsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/knowledge-sources': typeof AdminKnowledgeSourcesRoute
  '/admin/mcp-servers': typeof AdminMcpServersRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/url-monitor': typeof AdminUrlMonitorRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/helping-children-deal-with-grief': typeof ArticlesHelpingChildrenDealWithGriefRoute
  '/knowledge-base/$id': typeof KnowledgeBaseIdRoute
  '/admin': typeof AdminIndexRoute
  '/knowledge-base': typeof KnowledgeBaseIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/content/calendar': typeof AdminContentCalendarRoute
  '/admin/content/email-templates': typeof AdminContentEmailTemplatesRoute
  '/admin/conversations/$id': typeof AdminConversationsIdRoute
  '/admin/conversations/flagged': typeof AdminConversationsFlaggedRoute
  '/admin/insights/cohorts': typeof AdminInsightsCohortsRoute
  '/admin/insights/funnel': typeof AdminInsightsFunnelRoute
  '/admin/insights/sentiment': typeof AdminInsightsSentimentRoute
  '/admin/insights/themes': typeof AdminInsightsThemesRoute
  '/admin/ops/api-keys': typeof AdminOpsApiKeysRoute
  '/admin/ops/billing': typeof AdminOpsBillingRoute
  '/admin/ops/changelog': typeof AdminOpsChangelogRoute
  '/admin/ops/notifications': typeof AdminOpsNotificationsRoute
  '/admin/ops/roles': typeof AdminOpsRolesRoute
  '/admin/ops/team': typeof AdminOpsTeamRoute
  '/admin/safety/audit-log': typeof AdminSafetyAuditLogRoute
  '/admin/safety/escalations': typeof AdminSafetyEscalationsRoute
  '/admin/safety/guardrails': typeof AdminSafetyGuardrailsRoute
  '/admin/safety/policies': typeof AdminSafetyPoliciesRoute
  '/admin/agents': typeof AdminAgentsIndexRoute
  '/admin/conversations': typeof AdminConversationsIndexRoute
  '/admin/insights': typeof AdminInsightsIndexRoute
  '/admin/content/articles/$id': typeof AdminContentArticlesIdRoute
  '/admin/content/articles': typeof AdminContentArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-backup': typeof AboutBackupRoute
  '/admin': typeof AdminRouteWithChildren
  '/at-a-glance': typeof AtAGlanceRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/daily-affirmation': typeof DailyAffirmationRoute
  '/dashboard': typeof DashboardRoute
  '/faqs': typeof FaqsRoute
  '/journal': typeof JournalRoute
  '/navigator': typeof NavigatorRoute
  '/onboarding': typeof OnboardingRoute
  '/resource-library': typeof ResourceLibraryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support-groups': typeof SupportGroupsRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/email-captures': typeof AdminEmailCapturesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/journal-prompts': typeof AdminJournalPromptsRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/knowledge-sources': typeof AdminKnowledgeSourcesRoute
  '/admin/mcp-servers': typeof AdminMcpServersRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/url-monitor': typeof AdminUrlMonitorRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/helping-children-deal-with-grief': typeof ArticlesHelpingChildrenDealWithGriefRoute
  '/knowledge-base/$id': typeof KnowledgeBaseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/content/calendar': typeof AdminContentCalendarRoute
  '/admin/content/email-templates': typeof AdminContentEmailTemplatesRoute
  '/admin/conversations/$id': typeof AdminConversationsIdRoute
  '/admin/conversations/flagged': typeof AdminConversationsFlaggedRoute
  '/admin/insights/cohorts': typeof AdminInsightsCohortsRoute
  '/admin/insights/funnel': typeof AdminInsightsFunnelRoute
  '/admin/insights/sentiment': typeof AdminInsightsSentimentRoute
  '/admin/insights/themes': typeof AdminInsightsThemesRoute
  '/admin/ops/api-keys': typeof AdminOpsApiKeysRoute
  '/admin/ops/billing': typeof AdminOpsBillingRoute
  '/admin/ops/changelog': typeof AdminOpsChangelogRoute
  '/admin/ops/notifications': typeof AdminOpsNotificationsRoute
  '/admin/ops/roles': typeof AdminOpsRolesRoute
  '/admin/ops/team': typeof AdminOpsTeamRoute
  '/admin/safety/audit-log': typeof AdminSafetyAuditLogRoute
  '/admin/safety/escalations': typeof AdminSafetyEscalationsRoute
  '/admin/safety/guardrails': typeof AdminSafetyGuardrailsRoute
  '/admin/safety/policies': typeof AdminSafetyPoliciesRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/conversations/': typeof AdminConversationsIndexRoute
  '/admin/insights/': typeof AdminInsightsIndexRoute
  '/admin/content/articles/$id': typeof AdminContentArticlesIdRoute
  '/admin/content/articles/': typeof AdminContentArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-backup'
    | '/admin'
    | '/at-a-glance'
    | '/auth'
    | '/contact'
    | '/daily-affirmation'
    | '/dashboard'
    | '/faqs'
    | '/journal'
    | '/navigator'
    | '/onboarding'
    | '/resource-library'
    | '/services'
    | '/sitemap.xml'
    | '/support-groups'
    | '/admin/ai-models'
    | '/admin/ai-usage'
    | '/admin/email-captures'
    | '/admin/integrations'
    | '/admin/journal-prompts'
    | '/admin/knowledge-base'
    | '/admin/knowledge-sources'
    | '/admin/mcp-servers'
    | '/admin/memory'
    | '/admin/url-monitor'
    | '/admin/users'
    | '/articles/helping-children-deal-with-grief'
    | '/knowledge-base/$id'
    | '/admin/'
    | '/knowledge-base/'
    | '/admin/agents/$agentId'
    | '/admin/content/calendar'
    | '/admin/content/email-templates'
    | '/admin/conversations/$id'
    | '/admin/conversations/flagged'
    | '/admin/insights/cohorts'
    | '/admin/insights/funnel'
    | '/admin/insights/sentiment'
    | '/admin/insights/themes'
    | '/admin/ops/api-keys'
    | '/admin/ops/billing'
    | '/admin/ops/changelog'
    | '/admin/ops/notifications'
    | '/admin/ops/roles'
    | '/admin/ops/team'
    | '/admin/safety/audit-log'
    | '/admin/safety/escalations'
    | '/admin/safety/guardrails'
    | '/admin/safety/policies'
    | '/admin/agents/'
    | '/admin/conversations/'
    | '/admin/insights/'
    | '/admin/content/articles/$id'
    | '/admin/content/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-backup'
    | '/at-a-glance'
    | '/auth'
    | '/contact'
    | '/daily-affirmation'
    | '/dashboard'
    | '/faqs'
    | '/journal'
    | '/navigator'
    | '/onboarding'
    | '/resource-library'
    | '/services'
    | '/sitemap.xml'
    | '/support-groups'
    | '/admin/ai-models'
    | '/admin/ai-usage'
    | '/admin/email-captures'
    | '/admin/integrations'
    | '/admin/journal-prompts'
    | '/admin/knowledge-base'
    | '/admin/knowledge-sources'
    | '/admin/mcp-servers'
    | '/admin/memory'
    | '/admin/url-monitor'
    | '/admin/users'
    | '/articles/helping-children-deal-with-grief'
    | '/knowledge-base/$id'
    | '/admin'
    | '/knowledge-base'
    | '/admin/agents/$agentId'
    | '/admin/content/calendar'
    | '/admin/content/email-templates'
    | '/admin/conversations/$id'
    | '/admin/conversations/flagged'
    | '/admin/insights/cohorts'
    | '/admin/insights/funnel'
    | '/admin/insights/sentiment'
    | '/admin/insights/themes'
    | '/admin/ops/api-keys'
    | '/admin/ops/billing'
    | '/admin/ops/changelog'
    | '/admin/ops/notifications'
    | '/admin/ops/roles'
    | '/admin/ops/team'
    | '/admin/safety/audit-log'
    | '/admin/safety/escalations'
    | '/admin/safety/guardrails'
    | '/admin/safety/policies'
    | '/admin/agents'
    | '/admin/conversations'
    | '/admin/insights'
    | '/admin/content/articles/$id'
    | '/admin/content/articles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-backup'
    | '/admin'
    | '/at-a-glance'
    | '/auth'
    | '/contact'
    | '/daily-affirmation'
    | '/dashboard'
    | '/faqs'
    | '/journal'
    | '/navigator'
    | '/onboarding'
    | '/resource-library'
    | '/services'
    | '/sitemap.xml'
    | '/support-groups'
    | '/admin/ai-models'
    | '/admin/ai-usage'
    | '/admin/email-captures'
    | '/admin/integrations'
    | '/admin/journal-prompts'
    | '/admin/knowledge-base'
    | '/admin/knowledge-sources'
    | '/admin/mcp-servers'
    | '/admin/memory'
    | '/admin/url-monitor'
    | '/admin/users'
    | '/articles/helping-children-deal-with-grief'
    | '/knowledge-base/$id'
    | '/admin/'
    | '/knowledge-base/'
    | '/admin/agents/$agentId'
    | '/admin/content/calendar'
    | '/admin/content/email-templates'
    | '/admin/conversations/$id'
    | '/admin/conversations/flagged'
    | '/admin/insights/cohorts'
    | '/admin/insights/funnel'
    | '/admin/insights/sentiment'
    | '/admin/insights/themes'
    | '/admin/ops/api-keys'
    | '/admin/ops/billing'
    | '/admin/ops/changelog'
    | '/admin/ops/notifications'
    | '/admin/ops/roles'
    | '/admin/ops/team'
    | '/admin/safety/audit-log'
    | '/admin/safety/escalations'
    | '/admin/safety/guardrails'
    | '/admin/safety/policies'
    | '/admin/agents/'
    | '/admin/conversations/'
    | '/admin/insights/'
    | '/admin/content/articles/$id'
    | '/admin/content/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutBackupRoute: typeof AboutBackupRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtAGlanceRoute: typeof AtAGlanceRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DailyAffirmationRoute: typeof DailyAffirmationRoute
  DashboardRoute: typeof DashboardRoute
  FaqsRoute: typeof FaqsRoute
  JournalRoute: typeof JournalRoute
  NavigatorRoute: typeof NavigatorRoute
  OnboardingRoute: typeof OnboardingRoute
  ResourceLibraryRoute: typeof ResourceLibraryRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportGroupsRoute: typeof SupportGroupsRoute
  ArticlesHelpingChildrenDealWithGriefRoute: typeof ArticlesHelpingChildrenDealWithGriefRoute
  KnowledgeBaseIdRoute: typeof KnowledgeBaseIdRoute
  KnowledgeBaseIndexRoute: typeof KnowledgeBaseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support-groups': {
      id: '/support-groups'
      path: '/support-groups'
      fullPath: '/support-groups'
      preLoaderRoute: typeof SupportGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-library': {
      id: '/resource-library'
      path: '/resource-library'
      fullPath: '/resource-library'
      preLoaderRoute: typeof ResourceLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-affirmation': {
      id: '/daily-affirmation'
      path: '/daily-affirmation'
      fullPath: '/daily-affirmation'
      preLoaderRoute: typeof DailyAffirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/at-a-glance': {
      id: '/at-a-glance'
      path: '/at-a-glance'
      fullPath: '/at-a-glance'
      preLoaderRoute: typeof AtAGlanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-backup': {
      id: '/about-backup'
      path: '/about-backup'
      fullPath: '/about-backup'
      preLoaderRoute: typeof AboutBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base/': {
      id: '/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof KnowledgeBaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/knowledge-base/$id': {
      id: '/knowledge-base/$id'
      path: '/knowledge-base/$id'
      fullPath: '/knowledge-base/$id'
      preLoaderRoute: typeof KnowledgeBaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/helping-children-deal-with-grief': {
      id: '/articles/helping-children-deal-with-grief'
      path: '/articles/helping-children-deal-with-grief'
      fullPath: '/articles/helping-children-deal-with-grief'
      preLoaderRoute: typeof ArticlesHelpingChildrenDealWithGriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/url-monitor': {
      id: '/admin/url-monitor'
      path: '/url-monitor'
      fullPath: '/admin/url-monitor'
      preLoaderRoute: typeof AdminUrlMonitorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memory': {
      id: '/admin/memory'
      path: '/memory'
      fullPath: '/admin/memory'
      preLoaderRoute: typeof AdminMemoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mcp-servers': {
      id: '/admin/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/admin/mcp-servers'
      preLoaderRoute: typeof AdminMcpServersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge-sources': {
      id: '/admin/knowledge-sources'
      path: '/knowledge-sources'
      fullPath: '/admin/knowledge-sources'
      preLoaderRoute: typeof AdminKnowledgeSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge-base': {
      id: '/admin/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/admin/knowledge-base'
      preLoaderRoute: typeof AdminKnowledgeBaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/journal-prompts': {
      id: '/admin/journal-prompts'
      path: '/journal-prompts'
      fullPath: '/admin/journal-prompts'
      preLoaderRoute: typeof AdminJournalPromptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-captures': {
      id: '/admin/email-captures'
      path: '/email-captures'
      fullPath: '/admin/email-captures'
      preLoaderRoute: typeof AdminEmailCapturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-usage': {
      id: '/admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/admin/ai-usage'
      preLoaderRoute: typeof AdminAiUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-models': {
      id: '/admin/ai-models'
      path: '/ai-models'
      fullPath: '/admin/ai-models'
      preLoaderRoute: typeof AdminAiModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights/': {
      id: '/admin/insights/'
      path: '/insights'
      fullPath: '/admin/insights/'
      preLoaderRoute: typeof AdminInsightsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations/': {
      id: '/admin/conversations/'
      path: '/conversations'
      fullPath: '/admin/conversations/'
      preLoaderRoute: typeof AdminConversationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents/': {
      id: '/admin/agents/'
      path: '/agents'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AdminAgentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety/policies': {
      id: '/admin/safety/policies'
      path: '/safety/policies'
      fullPath: '/admin/safety/policies'
      preLoaderRoute: typeof AdminSafetyPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety/guardrails': {
      id: '/admin/safety/guardrails'
      path: '/safety/guardrails'
      fullPath: '/admin/safety/guardrails'
      preLoaderRoute: typeof AdminSafetyGuardrailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety/escalations': {
      id: '/admin/safety/escalations'
      path: '/safety/escalations'
      fullPath: '/admin/safety/escalations'
      preLoaderRoute: typeof AdminSafetyEscalationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety/audit-log': {
      id: '/admin/safety/audit-log'
      path: '/safety/audit-log'
      fullPath: '/admin/safety/audit-log'
      preLoaderRoute: typeof AdminSafetyAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/team': {
      id: '/admin/ops/team'
      path: '/ops/team'
      fullPath: '/admin/ops/team'
      preLoaderRoute: typeof AdminOpsTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/roles': {
      id: '/admin/ops/roles'
      path: '/ops/roles'
      fullPath: '/admin/ops/roles'
      preLoaderRoute: typeof AdminOpsRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/notifications': {
      id: '/admin/ops/notifications'
      path: '/ops/notifications'
      fullPath: '/admin/ops/notifications'
      preLoaderRoute: typeof AdminOpsNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/changelog': {
      id: '/admin/ops/changelog'
      path: '/ops/changelog'
      fullPath: '/admin/ops/changelog'
      preLoaderRoute: typeof AdminOpsChangelogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/billing': {
      id: '/admin/ops/billing'
      path: '/ops/billing'
      fullPath: '/admin/ops/billing'
      preLoaderRoute: typeof AdminOpsBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ops/api-keys': {
      id: '/admin/ops/api-keys'
      path: '/ops/api-keys'
      fullPath: '/admin/ops/api-keys'
      preLoaderRoute: typeof AdminOpsApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights/themes': {
      id: '/admin/insights/themes'
      path: '/insights/themes'
      fullPath: '/admin/insights/themes'
      preLoaderRoute: typeof AdminInsightsThemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights/sentiment': {
      id: '/admin/insights/sentiment'
      path: '/insights/sentiment'
      fullPath: '/admin/insights/sentiment'
      preLoaderRoute: typeof AdminInsightsSentimentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights/funnel': {
      id: '/admin/insights/funnel'
      path: '/insights/funnel'
      fullPath: '/admin/insights/funnel'
      preLoaderRoute: typeof AdminInsightsFunnelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights/cohorts': {
      id: '/admin/insights/cohorts'
      path: '/insights/cohorts'
      fullPath: '/admin/insights/cohorts'
      preLoaderRoute: typeof AdminInsightsCohortsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations/flagged': {
      id: '/admin/conversations/flagged'
      path: '/conversations/flagged'
      fullPath: '/admin/conversations/flagged'
      preLoaderRoute: typeof AdminConversationsFlaggedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations/$id': {
      id: '/admin/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/admin/conversations/$id'
      preLoaderRoute: typeof AdminConversationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/email-templates': {
      id: '/admin/content/email-templates'
      path: '/content/email-templates'
      fullPath: '/admin/content/email-templates'
      preLoaderRoute: typeof AdminContentEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/calendar': {
      id: '/admin/content/calendar'
      path: '/content/calendar'
      fullPath: '/admin/content/calendar'
      preLoaderRoute: typeof AdminContentCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents/$agentId': {
      id: '/admin/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AdminAgentsAgentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/articles/': {
      id: '/admin/content/articles/'
      path: '/content/articles'
      fullPath: '/admin/content/articles/'
      preLoaderRoute: typeof AdminContentArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/articles/$id': {
      id: '/admin/content/articles/$id'
      path: '/content/articles/$id'
      fullPath: '/admin/content/articles/$id'
      preLoaderRoute: typeof AdminContentArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiModelsRoute: typeof AdminAiModelsRoute
  AdminAiUsageRoute: typeof AdminAiUsageRoute
  AdminEmailCapturesRoute: typeof AdminEmailCapturesRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminJournalPromptsRoute: typeof AdminJournalPromptsRoute
  AdminKnowledgeBaseRoute: typeof AdminKnowledgeBaseRoute
  AdminKnowledgeSourcesRoute: typeof AdminKnowledgeSourcesRoute
  AdminMcpServersRoute: typeof AdminMcpServersRoute
  AdminMemoryRoute: typeof AdminMemoryRoute
  AdminUrlMonitorRoute: typeof AdminUrlMonitorRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAgentsAgentIdRoute: typeof AdminAgentsAgentIdRoute
  AdminContentCalendarRoute: typeof AdminContentCalendarRoute
  AdminContentEmailTemplatesRoute: typeof AdminContentEmailTemplatesRoute
  AdminConversationsIdRoute: typeof AdminConversationsIdRoute
  AdminConversationsFlaggedRoute: typeof AdminConversationsFlaggedRoute
  AdminInsightsCohortsRoute: typeof AdminInsightsCohortsRoute
  AdminInsightsFunnelRoute: typeof AdminInsightsFunnelRoute
  AdminInsightsSentimentRoute: typeof AdminInsightsSentimentRoute
  AdminInsightsThemesRoute: typeof AdminInsightsThemesRoute
  AdminOpsApiKeysRoute: typeof AdminOpsApiKeysRoute
  AdminOpsBillingRoute: typeof AdminOpsBillingRoute
  AdminOpsChangelogRoute: typeof AdminOpsChangelogRoute
  AdminOpsNotificationsRoute: typeof AdminOpsNotificationsRoute
  AdminOpsRolesRoute: typeof AdminOpsRolesRoute
  AdminOpsTeamRoute: typeof AdminOpsTeamRoute
  AdminSafetyAuditLogRoute: typeof AdminSafetyAuditLogRoute
  AdminSafetyEscalationsRoute: typeof AdminSafetyEscalationsRoute
  AdminSafetyGuardrailsRoute: typeof AdminSafetyGuardrailsRoute
  AdminSafetyPoliciesRoute: typeof AdminSafetyPoliciesRoute
  AdminAgentsIndexRoute: typeof AdminAgentsIndexRoute
  AdminConversationsIndexRoute: typeof AdminConversationsIndexRoute
  AdminInsightsIndexRoute: typeof AdminInsightsIndexRoute
  AdminContentArticlesIdRoute: typeof AdminContentArticlesIdRoute
  AdminContentArticlesIndexRoute: typeof AdminContentArticlesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiModelsRoute: AdminAiModelsRoute,
  AdminAiUsageRoute: AdminAiUsageRoute,
  AdminEmailCapturesRoute: AdminEmailCapturesRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminJournalPromptsRoute: AdminJournalPromptsRoute,
  AdminKnowledgeBaseRoute: AdminKnowledgeBaseRoute,
  AdminKnowledgeSourcesRoute: AdminKnowledgeSourcesRoute,
  AdminMcpServersRoute: AdminMcpServersRoute,
  AdminMemoryRoute: AdminMemoryRoute,
  AdminUrlMonitorRoute: AdminUrlMonitorRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAgentsAgentIdRoute: AdminAgentsAgentIdRoute,
  AdminContentCalendarRoute: AdminContentCalendarRoute,
  AdminContentEmailTemplatesRoute: AdminContentEmailTemplatesRoute,
  AdminConversationsIdRoute: AdminConversationsIdRoute,
  AdminConversationsFlaggedRoute: AdminConversationsFlaggedRoute,
  AdminInsightsCohortsRoute: AdminInsightsCohortsRoute,
  AdminInsightsFunnelRoute: AdminInsightsFunnelRoute,
  AdminInsightsSentimentRoute: AdminInsightsSentimentRoute,
  AdminInsightsThemesRoute: AdminInsightsThemesRoute,
  AdminOpsApiKeysRoute: AdminOpsApiKeysRoute,
  AdminOpsBillingRoute: AdminOpsBillingRoute,
  AdminOpsChangelogRoute: AdminOpsChangelogRoute,
  AdminOpsNotificationsRoute: AdminOpsNotificationsRoute,
  AdminOpsRolesRoute: AdminOpsRolesRoute,
  AdminOpsTeamRoute: AdminOpsTeamRoute,
  AdminSafetyAuditLogRoute: AdminSafetyAuditLogRoute,
  AdminSafetyEscalationsRoute: AdminSafetyEscalationsRoute,
  AdminSafetyGuardrailsRoute: AdminSafetyGuardrailsRoute,
  AdminSafetyPoliciesRoute: AdminSafetyPoliciesRoute,
  AdminAgentsIndexRoute: AdminAgentsIndexRoute,
  AdminConversationsIndexRoute: AdminConversationsIndexRoute,
  AdminInsightsIndexRoute: AdminInsightsIndexRoute,
  AdminContentArticlesIdRoute: AdminContentArticlesIdRoute,
  AdminContentArticlesIndexRoute: AdminContentArticlesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutBackupRoute: AboutBackupRoute,
  AdminRoute: AdminRouteWithChildren,
  AtAGlanceRoute: AtAGlanceRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DailyAffirmationRoute: DailyAffirmationRoute,
  DashboardRoute: DashboardRoute,
  FaqsRoute: FaqsRoute,
  JournalRoute: JournalRoute,
  NavigatorRoute: NavigatorRoute,
  OnboardingRoute: OnboardingRoute,
  ResourceLibraryRoute: ResourceLibraryRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportGroupsRoute: SupportGroupsRoute,
  ArticlesHelpingChildrenDealWithGriefRoute:
    ArticlesHelpingChildrenDealWithGriefRoute,
  KnowledgeBaseIdRoute: KnowledgeBaseIdRoute,
  KnowledgeBaseIndexRoute: KnowledgeBaseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
